apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-task-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 80
