name: Deployment

on:
  push:
    branches:
      - main
      - master

jobs:
  run-inline-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script
        run: |
          echo "Running deployment script..."
          sudo apt-get update
          sudo apt-get install -y unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          echo "printing caller identity to test aws cli"
          aws sts get-caller-identity
          echo "installing kubectl"
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          chmod +x kubectl
          mkdir -p ~/.local/bin
          mv ./kubectl ~/.local/bin/kubectl
          kubectl version --client
          aws eks update-kubeconfig --name devops-task-cluster --region eu-west-2
          kubectl get pods
          docker build -t task-app:latest
          kubectl set image deployment task-app=task-app:latest
          sleep 2
          kubectl rollout restart deployment task-app-deployment
          

          
